{
 "title": "Hospital monitoring system",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Patient C02 - STATUS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM patients\nWHERE\n  $__timeFilter(time) AND URI = 'coap://[fd00:0:0:0:202:2:2:2]/temperature'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Patient C03 - STATUS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Temperature" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM patients\nWHERE\n  $__timeFilter(time) AND URI = 'coap://[fd00:0:0:0:203:3:3:3]/temperature'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Patient C04 - STATUS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Temperature" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM patients\nWHERE\n  $__timeFilter(time) AND URI = 'coap://[fd00:0:0:0:204:4:4:4]/temperature'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Patient C05 - STATUS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Temperature" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM patients\nWHERE\n  $__timeFilter(time) AND URI = 'coap://[fd00:0:0:0:205:5:5:5]/temperature'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Patient M48033 - STATUS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM patients\nWHERE\n  $__timeFilter(time) AND URI = 'mqtt1://48033'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Patient M38538 - STATUS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM patients\nWHERE\n  $__timeFilter(time) AND URI = 'mqtt1://38538'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Patient M61370 - STATUS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  value\nFROM patients\nWHERE\n  $__timeFilter(time) AND URI = 'mqtt1://61370'\nORDER BY time"
    }
   ]
  },
  { "type": "welcome", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 } },
  { "title": "Latest from the blog", "type": "news", "gridPos": { "h": 15, "w": 12, "x": 12, "y": 40 } }
 ]
}